#!/bin/sh
alias ls='ls --color=auto'
alias la='ls -a --color=auto'
alias l='ls -1 --color=auto'
alias lah='ls -lah --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color'

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"

alias lls='ls | lolcat'
alias ltop='htop | lolcat'
alias cls='lah | lolcrab -i'

alias s='sudo pacman -S'
alias syu='sudo pacman -Syu'
alias ss='paru -Ss'
alias i='pacman -Si'
alias q='pacman -Q'
alias r='sudo pacman -Rsn'
alias y='paru -S'
alias ar='sudo pacman -Rcns $(pacman -Qdtq)'

alias gad='git add'
alias gst='git status'
alias gcm='git commit'
alias ECM='git commit --allow-empty-message'
alias gph='git push'
alias gpa='git push --all'
alias gcl='git clone `xclip -out -selection clipboard`'
alias gco='git checkout'
alias glt='git log --oneline --decorate --graph --all'
alias glta='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --all'

# DEV
alias cargo-t='cargo test -- --nocapture'
alias cr='cargo run'
alias cre='cargo run --example'
alias crr='cargo run --release'
alias pypy='pypy3'

alias vi='nvim -u NONE'
alias v='nvim'
alias V="sudoedit"
alias z="zathura"
alias rtop="radeontop -c"

# notebook
alias note='cd ~/Documents/notes && nvim index.md'
alias utm='cd ~/Documents/notes/UTM && nvim index.md'
alias anime='nvim ~/Documents/notes/Journal/Entertaiment/index.md'
alias quote='nvim ~/Documents/notes/Journal/quotes/index.md'
alias books='nvim ~/Documents/notes/Journal/books/books.md'
alias ideas='nvim ~/Documents/notes/ideas.md'

# labs
cd_last_lab() { cd $1 && cd $(ls -dv */ | grep lab | tail -n 1) }

# generates alias for all objects; wont cd in latest lab

for an in ~/UTM/*an; do
     for sem in $an/*sem; do
         for D in $sem/*/; do
             obiect=$(basename ${D})
             alias $obiect="cd $D" 
             alias "${obiect}_"="cd_last_lab $D" 
         done
         alias $(basename ${sem})="cd $sem"
     done
done
alias an='cd ~/UTM/ii_an/iii_sem/apa/an'


# edit config
alias evim="nvim ~/.config/nvim/init.vim"
alias etmux="nvim ~/.config/tmux/tmux.conf"
alias equtebrowser="nvim ~/.config/qutebrowser/config.py"
alias eqsearch="nvim ~/.config/qutebrowser/modules/search_engines.py"
alias eqbindings="nvim ~/.config/qutebrowser/modules/bindings.py"
alias esxhkd="nvim ~/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd"
alias esh="nvim ~/.config/shell/alias && source ~/.config/shell/alias"
alias eenv="nvim ~/.config/shell/env && source ~/.config/shell/env"
alias ezsh="nvim ~/.config/zsh/.zshrc && source ~/.config/zsh/.zshrc"
alias erofi="nvim ~/.config/rofi/config.rasi"

# MISC
alias myip="curl http://ipecho.net/plain; echo"
alias o="xdg-open"
alias b=$BROWSER
alias reflector='sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist'
alias code=codium
alias unimatrix='unimatrix -s 95'
alias disc='python ~/code/python/discord_shell.py'
alias neofetch='neofetch --ascii_distro FreeBSD'
alias mtux='tmux new-session -A -s main'

alias wget_website='wget --recursive --no-clobber --page-requisites  --html-extension  --convert-links  --restrict-file-names=windows  --domains website.org  --no-parent '

# window manager
alias sx2='sx ~/.config/sx/sxrc'
alias kde='sx /bin/startplasma-x11'
alias sxd='sx2 dwm'
alias tray='trayer --edge top --align right --width 25'

alias wifi-list='nmcli dev wifi list'
alias wifi-connect='nmcli dev wifi connect'

alias pdf_presentation='libreoffice --headless --convert-to pdf *.pp* --outdir ./out'
alias pdfjoin='pdfjam --fitpaper true --suffix joined'

