#blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

#[line_break]
#disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol= "[✖](bold red)"
vicmd_symbol="[❮](bold yellow)"

[username]
format = "[$user](bold bright-blue)@"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold red):"
disabled = false

[directory]
truncation_symbol = "/"
truncation_length = 2
truncate_to_repo = false
home_symbol = "~"
style = "bold bright-green"
