#!/bin/sh
xrandr --output eDP --mode 1280x720 --set TearFree on &
# xrandr --output DisplayPort-0 --set TearFree on
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
setxkbmap -option caps:super &
libinput-gestures-setup start &
# xset r rate 900 1 &
xrdb $XDG_CONFIG_HOME/x11/Xresources &
pulseaudio --daemonize &
picom &
sxhkd &
lxpolkit &
dunst &
nm-applet &
flameshot &
nitrogen --restore &
# wallpapersd &
$TERMINAL -e tmux new-session -A -s main&
dwmbar.sh&
# asus_monitor&
