-- roslyn bindings
map("n", "K", vim.lsp.buf.hover, "LSP Hover")
map("n", "gi", vim.lsp.buf.implementation, "LSP Go to Implementation")
map("n", "<C-k>", vim.lsp.buf.signature_help, "LSP Signature help")
map("n", "<leader>wa", vim.lsp.buf.add_workspace_folder, "LSP Workspace add")
map("n", "<leader>wr", vim.lsp.buf.remove_workspace_folder, "LSP Workspace remove")
map("n", "<leader>wl", function()
  print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end, "WS list")
map("n", "<leader>ra", vim.lsp.buf.rename, "LSP Rename")
map("n", "<leader>ca", vim.lsp.buf.code_action, "LSP Code action")
map("v", "<leader>ca", vim.lsp.buf.code_action, "LSP Code action")
map("n", "<F12>", vim.lsp.buf.definition, "LSP Definition")
map("n", "gr", require("fzf-lua").lsp_references, "References")
