#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

# second monitor
bspc config -m HDMI-A-0 top_padding 0
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

bspc config -m eDP top_padding 20
bspc config border_width        3 
bspc config window_gap          2
bspc config focused_border_color "#6454A1"
bspc config normal_border_color "#323248"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

nm-applet &
# polybar example &
~/.config/polybar/launch.sh
