#!/bin/sh
alias ls='ls --color=auto'
alias la='ls -a --color=auto'
alias l='ls -l --color=auto'
alias lah='ls -lah --color=auto'
alias grep='grep --color=auto'

alias lls='ls | lolcat'

alias s='doas pacman -S'
alias ss='pacman -Ss'
alias i='pacman -Si'
alias r='doas pacman -Rsn'
alias y='yay -S'
alias q='pacman -Q'
alias ar='doas pacman -Rcns $(pacman -Qdtq)'

alias gad='git add'
alias gst='git status'
alias ecm='git commit --allow-empty-message'
alias gph='git push'
alias gcl='git clone `xclip -out -selection clipboard`'

alias vim='nvim'
alias v='nvim'

alias z="zathura"

alias note='cd ~/Documents/notes && vim index.md'
alias qnote='nvim ~/Documents/notes/QuickNote.md'
alias todo='cd ~/Documents/notes && vim todo.txt'
alias ntbak='rsync /home/catalin/Documents/notes/ /media/catalin/catalin/notes -r'

alias evim="nvim ~/.config/nvim/init.vim"
alias eqtile="nvim ~/.config/qtile/config.py"
alias equtebrowser="nvim ~/.config/qutebrowser/config.py"
alias esxhkd="nvim ~/.config/sxhkd/sxhkdrc"

alias myip="curl http://ipecho.net/plain; echo"
alias o="xdg-open"
alias stx='startx "$XDG_CONFIG_HOME/X11/xinitrc" -- "$XDG_CONFIG_HOME/X11/xserverrc" vt1'
