#!/bin/sh
. $XDG_CONFIG_HOME/x11/xprofile 

case $1 in
	qtile			  ) exec qtile start;;
    kde               ) exec startplasma-x11;;
    gnome             ) exec gnome-shell;;
    bspwm             ) exec bspwm;;
    openbox           ) exec openbox;;
    dwm				  ) exec dwm;;
    *                 ) exec dwm;;

esac
