#!/bin/sh
. $XDG_CONFIG_HOME/x11/xprofile 

case $1 in
	qtile			  ) exec qtile start;;
    kde               ) exec startplasma-x11;;
    bspwm             ) exec bspwm;;
    # openbox           ) exec openbox;;
    *                 ) exec qtile start;;
esac

# exec qtile start 
