xrdb $XDG_CONFIG_HOME/x11/Xresources &
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
picom &
#picom --config /dev/null -i 0.8 --inactive-dim 0.2 &
sxhkd &
lxpolkit &
dunst &
nm-applet &
nitrogen --restore &
emote &

setxkbmap -option caps:super &
xset r rate 900 1 &

kitty &
# xrandr --output eDP --mode 1280x720

exec qtile start
