#!/bin/bash

# --- CONFIGURATION ---
# Add your repo paths here
REPOS=(
    "$HOME/Documents/wiki/delta"
    # "/home/catalin/another-repo"
)

BIN_DIR="$HOME/.local/bin"
LIST_FILE="$HOME/.config/systemd/user/repo-list"
SYNC_SCRIPT="$BIN_DIR/git-sync-all.sh"
USER_UNIT_DIR="$HOME/.config/systemd/user"

mkdir -p "$BIN_DIR" "$USER_UNIT_DIR"

install() {
    echo "1. Creating Repo List..."
    printf "%s\n" "${REPOS[@]}" > "$LIST_FILE"

    echo "2. Creating Sync Script..."
    cat <<EOF > "$SYNC_SCRIPT"
#!/bin/bash
# Automatically generated by install-sync.sh
while read -r REPO; do
    [[ -z "\$REPO" || "\$REPO" =~ ^# ]] && continue
    if [[ -d "\$REPO/.git" ]]; then
        cd "\$REPO" || continue
        # Handle dirty worktree so rebase doesn't fail
        git stash push -m "auto-sync-stash"
        git pull --rebase
        git add .
        if ! git diff-index --quiet HEAD --; then
            git commit -m "Auto-sync [\$(date '+%Y-%m-%d %H:%M:%S')] on \$(hostname)"
            git push
        fi
        git stash pop || true
    fi
done < "$LIST_FILE"
EOF
    chmod +x "$SYNC_SCRIPT"

    echo "3. Creating Systemd Service..."
    cat <<EOF > "$USER_UNIT_DIR/git-sync.service"
[Unit]
Description=Sync all git repos
After=network.target

[Service]
Type=oneshot
ExecStart=$SYNC_SCRIPT
EOF

    echo "4. Creating Systemd Timer (5 min)..."
    cat <<EOF > "$USER_UNIT_DIR/git-sync.timer"
[Unit]
Description=Run git sync every 5 minutes

[Timer]
OnCalendar=*:0/5
Persistent=true

[Install]
WantedBy=timers.target
EOF

    systemctl --user daemon-reload
    systemctl --user enable --now git-sync.timer
    echo "SUCCESS: Timer active. Check logs with: journalctl --user -u git-sync.service -f"
}

uninstall() {
    systemctl --user disable --now git-sync.timer
    rm -f "$USER_UNIT_DIR/git-sync.service" "$USER_UNIT_DIR/git-sync.timer" "$LIST_FILE" "$SYNC_SCRIPT"
    systemctl --user daemon-reload
    echo "Uninstalled."
}

case "$1" in
    install) install ;;
    uninstall) uninstall ;;
    *) echo "Usage: $0 {install|uninstall}" ;;
esac
