#!/bin/sh

black='#282828'
black0='#7c6f64'
red='#cc241d'
red0='#fb4934'
green='#98971a'
green0='#b8bb26'
yellow='#d79921'
yellow0='#fabd2f'
blue='#458588'
blue0='#83a598'
purple='#b16286'
purple0='#d3869b'
aqua='#689d6a'
aqua0='#8ec07c'
white='#a89984'
white0='#fbf1c7'
fg(){
    echo "^c$1^"
}
bg(){
    echo "^b$1^"
}

cpu=$(grep 'cpu ' /proc/stat | awk '{printf("%.1f"), ($2+$4)*100/($2+$4+$5)}')
# echo -n "[CPU $cpu%]"
# echo -n "$(fg $black)$(bg $red)[CPU: $cpu]"
echo -n "$(fg $red)[CPU:$cpu]"
