#!/bin/sh

black='#282828'
black0='#7c6f64'
red='#cc241d'
red0='#fb4934'
green='#98971a'
green0='#b8bb26'
yellow='#d79921'
yellow0='#fabd2f'
blue='#458588'
blue0='#83a598'
purple='#b16286'
purple0='#d3869b'
aqua='#689d6a'
aqua0='#8ec07c'
white='#a89984'
white0='#fbf1c7'
fg(){
    echo "^c$1^"
}
bg(){
    echo "^b$1^"
}


update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

download=$(printf "%4sB\\n" $(numfmt --to=iec $rx))
upload=$(printf "%4sB\\n" $(numfmt --to=iec $tx))


if [[ "$1" == "download" ]]; then
    # echo -n "$(fg $white0)$(bg $black)[$download ⬇]"
    echo -n "$(fg $white0)$(bg $black0)[$download ⬇]^d^"
fi

if [[ "$1" == "upload" ]]; then
    # echo -n "$(fg $black)$(bg $white0)[$upload ⬆]"
    echo -n "$(fg $white0)$(bg $black0)[$upload ⬆]^d^"
fi
