#!/bin/sh

source ~/.config/dwmblocks/scripts/progress_data
bars=$(($percent / 10))

empty="▱"
full="▰"
progress_bar=""

for i in {1..10}
do
    if [ "$bars" -gt 0 ]; then
        progress_bar="$progress_bar$full"
        bars=$(($percent-1))
    else
        progress_bar="$progress_bar$empty"
    fi
done

echo "$progress_bar $percent% <$message>"
