#!/bin/sh

source ~/.config/dwmblocks/scripts/progress_data
percent=0
message="In progress"

echo "percent=$percent" > ~/.config/dwmblocks/scripts/progress_data
echo 'message="$message"' >> ~/.config/dwmblocks/scripts/progress_data

for i in {1..100}
do
    percent=$(($percent + 1))
    echo "percent=$percent" > ~/.config/dwmblocks/scripts/progress_data
    echo "message=\"$message\"" >> ~/.config/dwmblocks/scripts/progress_data
    sleep 0.05s
done

percent=0
message="Waiting"
echo "percent=$percent" > ~/.config/dwmblocks/scripts/progress_data
echo "message=\"$message\"" >> ~/.config/dwmblocks/scripts/progress_data
