[ids]
*
# dactyl
-feed:0000	
# mouse
-1d50:615e
0fac:1ade
0002:000a
[main]
# https://millikeys.sourceforge.net/asset/
capslock = escape
altgr = layer(nav)
# leftmouse = leftshift
# rightmouse = leftcontrol
# middlemouse = overload(nav, backspace)
# leftcontrol = escape
102nd = leftcontrol

[nav]
leftbrace = M-leftbrace 
rightbrace = M-rightbrace 
a = leftmeta
s = leftalt
d = leftshift
f = leftcontrol
n = tab
q = M-q
space = M-space
enter = M-enter
b = M-b
0 = A-0
1 = A-1
2 = A-2
3 = A-3
4 = A-4
5 = A-5
6 = A-6
7 = A-7
8 = A-8
9 = A-9
u = home
i = pagedown
o = pageup
p = end
h = left
j = down
k = up
l = right
