#!/bin/sh 
adb disconnect
echo "plug device via usb"
adb wait-for-device
echo "device detected"
adb tcpip 6969
echo "tcpip paired port 6969"
sleep 3
IP=$(adb shell ip addr show wlan0  | grep 'inet ' | cut -d' ' -f6| cut -d/ -f1)
echo "device ip found ${IP}"
# echo "unplug then press enter"
# read
adb connect "${IP}:6969"
echo "you can unplug usb now"
