#!/bin/sh
backup_partition=/dev/sda2
destionation=/run/media/catalin/catalin
mkdir "$destionation"

sudo mount $backup_partition $destionation

rsync -aP --delete ~/.config $destination/configs
rsync -aP --delete ~/Books $destination
rsync -aP --delete ~/UTM $destination
rsync -aP ~/.ssh $destination/ssh
rsync -aP ~/Documents $destination
rsync -aP ~/Downloads $destination
rsync -aP ~/Music $destination
rsync -aP ~/Pictures $destination
rsync -aP ~/Sync $destination
rsync -aP ~/Videos $destination
rsync -aP ~/code $destination

sudo umount $destionation
rm -rf "$destionation"
