#!/bin/sh
YEAR=`date +%Y`
MONTH=`date +%B`

while getopts shnp:u: name
do
    case $name in
        s)    s_flag=1;;
        h)    h_flag=1;;
        n)    n_flag=1
            continue='y';;
        u)    url_flag=1
            url="$OPTARG";;
        p)    playlist_flag=1
            playlist="$OPTARG";;
        ?)    printf "Usage: %s: [-s] [-n] {-u {url}} [-p {playlist}]
            -s - single song
            -n - no confirm
            -u - url to youtube video or playlist
            -p - playlist name for dir in whichi it will be saved" $0
            exit 2;;
    esac
done

if [ ! -z "$h_flag" ]; then
    printf "Usage: [-s] [-n] {-u {url}} [-p {playlist}]
    -s - single song
    -n - no confirm
    -u - url to youtube video or playlist
    -p - playlist name for dir in whichi it will be saved"
    exit 0
fi

if [ -z "$url_flag" ] || [ -z "$url" ]; then
    printf "At least profide url"
    exit 0
fi

if test "${url#*index}" != "$url" -o "${url#*playlist}" != "$url" -o "${url#*radio}" != "$url"
then
    echo "PLAYLST DETECTED"
    if [ -z "$playlist_flag" ] || [ ! -z "$s_flag" ]; then
        download_dir=~/Music/$YEAR/$MONTH
    else
        download_dir=~/Music/$YEAR/playlists/$playlist
        MONTH=$playlist
    fi
else
    echo "SONG DETECTED"
    download_dir=~/Music/$YEAR/$MONTH
    s_flag=1
fi

echo "Download path: '$download_dir'"
echo -n "Continue the download [y/n]? "
if [ -z "$n_flag" ]
then
    read continue
fi

if [ ! "$continue" != "${continue#[Yy]}" ] ;then
    echo "see you later"
    exit 0
fi

notify-send "download started in '$download_dir'" -t 3000


mkdir -p $download_dir
cd $download_dir

if [ ! -z "$s_flag" ]; then
    echo "Downloading a single file"
    youtube-dl --ignore-errors --extract-audio --audio-format mp3 --audio-quality 0\
        --add-metadata --no-playlist --embed-thumbnail -o "%(title)s.%(ext)s" $url
        else
            echo "Downloading multiple files in paralell"

            youtube-dl --ignore-errors --get-id $url \
                | xargs -I '{}' -P 5 \
                sh -c 'youtube-dl --ignore-errors --extract-audio --audio-format mp3 --audio-quality 0 \
                --add-metadata --embed-thumbnail -o "%(title)s.%(ext)s" "https://youtube.com/watch?v={}"; (true)'

fi

notify-send "download finished" --urgency=low


if [ $(ps aux | grep muzd | grep -v grep | grep -v qute | wc -l) = 2 ]; then
    mkdir -p ~/Music/xiaomi/$MONTH
    cp -rn $download_dir/* ~/Music/xiaomi/$MONTH/

    notify-send -t 4000 "Sync" "<span color='#fabd2f' font='20px'><i><b>Music copyed to phone</b></i></span>"
fi
