#!/bin/sh
cd ~/Documents/notes

Y=`date +%Y`
B=`date +%B`
F=`date +%d_%m_%Y`
File="index.md"

if [ -z "$1" ]
  then
    Notebook="Journal"
else
	Notebook=$1
fi

mkdir -p "$Notebook/$Y/$B"
if ! grep -q "$Y" "$Notebook/$File"; then
	echo "- [$Y]($Y/index.md)" >> "$Notebook/$File"
fi
if ! grep -q "$B" "$Notebook/$Y/$File"; then
	echo "- [$B]($B/index.md)" >> "$Notebook/$Y/$File"
fi

if ! grep -q "$F" "$Notebook/$Y/$B/$File"; then
	echo "- [$F]($F.md)  " >> "$Notebook/$Y/$B/$File"
fi
# touch "$Notebook/$Y/$B/$F.md"
echo "[$(date +%T)]  " >> "$Notebook/$Y/$B/$F.md"
echo "" >> "$Notebook/$Y/$B/$F.md"

nvim -c "norm G" -c startinsert "$Notebook/$Y/$B/$F.md"
