#!/bin/sh
# script to change my desktop theme dark to light
FILE=$XDG_CONFIG_HOME/theme/conf
if [ -f "$FILE" ]
then
	theme=`cat $FILE` 
else
	echo "what is the curent theme [dark/light] "
	read theme
	mkdir -p $XDG_CONFIG_HOME/theme
	echo "$theme" > $FILE
fi

if [ "$theme" = "light" ]
then
	cp ~/.config/kitty/gruvbox/dark.conf ~/.config/kitty/colors.conf
	cp ~/.config/qtile/gruvbox/dark.py ~/.config/qtile/theme.py
	sed -i 's/Light/Dark/g' ~/.config/VSCodium/User/settings.json 
	sed -i 's/Light/Dark/g' ~/.config/wezterm/wezterm.lua
	sed -i 's/config.source("themes[^ ]*/config.source("themes\/gruvbox.py")/' ~/.config/qutebrowser/config.py  
	sed -i 's/fbf1c7/282828/' /home/catalin/.config/qutebrowser/startpage/common.css
	sed -i 's/fb4934/b8bb26/' /home/catalin/.config/qutebrowser/startpage/common.css
	sed -i 's/gruvbox-light/gruvbox-dark/' /home/catalin/.config/rofi/config.rasi
	sed -i 's/set background=light/set background=dark/' /home/catalin/.config/nvim/init.vim

	# nitrogen --set-zoom /home/catalin/Pictures/wallpapers/anime/anime_33.png
	theme="dark"
else
	cp ~/.config/kitty/gruvbox/light.conf ~/.config/kitty/colors.conf
	cp ~/.config/qtile/gruvbox/light.py ~/.config/qtile/theme.py
	sed -i 's/Dark/Light/g' ~/.config/VSCodium/User/settings.json
	sed -i 's/Dark/Light/g' ~/.config/wezterm/wezterm.lua 
	sed -i 's/config.source("themes[^ ]*/config.source("themes\/base16-gruvbox-light-medium.config.py")/' ~/.config/qutebrowser/config.py  
	sed -i 's/282828/fbf1c7/' /home/catalin/.config/qutebrowser/startpage/common.css
	sed -i 's/b8bb26/fb4934/' /home/catalin/.config/qutebrowser/startpage/common.css
	sed -i 's/gruvbox-dark/gruvbox-light/' /home/catalin/.config/rofi/config.rasi
	sed -i 's/set background=dark/set background=light/' /home/catalin/.config/nvim/init.vim

	# nitrogen --set-zoom ~/Pictures/wallpapers/anime/anime_19.jpg
	theme="light"
fi
pkill -USR1 -x kitty
qtile cmd-obj -o cmd -f restart
if  pgrep -x qutebrowser 
then
	qutebrowser ':reload'
	qutebrowser ':config-source'
fi 
echo "$theme" > $FILE
