#!/bin/sh
# to generate ungoogled chromium extension link
version='92.0.4515.131'
echo "https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=$version&x=id%3D$(xclip -o)%26installsource%3Dondemand%26uc" | xclip -sel clip
