#!/bin/sh
Y=`date +%Y`
B=`date +%B`
mkdir -p ~/Music/$Y/$B
cd ~/Music/$Y/$B
youtube-dl --ignore-errors --extract-audio --audio-format mp3 --audio-quality 0\
	--add-metadata --no-playlist --embed-thumbnail -o "%(title)s.%(ext)s" $1 
