#!/bin/sh
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
picom &
sxhkd &
lxpolkit &
dunst &
nm-applet &
nitrogen --restore &
emote &

setxkbmap -option caps:super &
xset r rate 900 1 &

kitty &
# xrandr --output eDP --mode 1280x720

exec qtile start
